# Generated by Django 5.0.1 on 2024-01-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', to='testusers.teacher'),
        ),
    ]
